### ISSUE TITLE
upgrade Ruby and Bundler

### ISSUE THREAD

**Issue by afeld** [wercker/box-ubuntu12.04-ruby2.0.0#1]
Ruby 2.0.0 is [no longer supported](https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/), and the installed version of Bundler is three years old. This is causing [problems with things like the `bundle-install` step](https://github.com/wercker/step-bundle-install/issues/14), which uses a flag that isn't supported in that version of Bundler. Upgrades to the latest versions of both would be great. Thanks!

**Comment by afeld** [comment]
Also, happy to move this issue to https://github.com/wercker/box-ruby if preferred.

**Comment by hatchan** [comment]
These boxes are not maintained anymore. We recommend switching to the new docker/workflows stack. 

If you need to keep using the legacy stack, then you can switch to the [box-rvm](https://github.com/wercker/box-rvm) box, which out of the box uses `ruby-2.3.1`. Otherwise you can fork this repository, make the changes, and publish the box under your own user.
